-- 1. INSERT USERS
INSERT INTO users (id, full_name, email, hash_password, hash_pin, phone, profile_picture_url, is_verified, created_at) VALUES
                                                                                                                           (1, 'Budi Santoso', 'budi.santoso@email.com', 'hash_budi123', '123456', '+6281111111111', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi', TRUE, NOW() - INTERVAL '400 days'),
                                                                                                                           (2, 'Siti Aminah', 'siti.aminah@email.com', 'hash_siti123', '234567', '+6281222222222', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti', TRUE, NOW() - INTERVAL '350 days'),
                                                                                                                           (3, 'Andi Wijaya', 'andi.wijaya@email.com', 'hash_andi123', '345678', '+6281333333333', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Andi', TRUE, NOW() - INTERVAL '300 days'),
                                                                                                                           (4, 'Dewi Lestari', 'dewi.lestari@email.com', 'hash_dewi123', '456789', '+6281444444444', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dewi', FALSE, NOW() - INTERVAL '250 days'),
                                                                                                                           (5, 'Eko Prasetyo', 'eko.prasetyo@email.com', 'hash_eko123', '567890', '+6281555555555', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eko', TRUE, NOW() - INTERVAL '200 days'),
                                                                                                                           (6, 'Fajar Hidayat', 'fajar.saputra@email.com', 'hash_fajar123', '100006', '+6281666666006', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fajar', TRUE, NOW() - INTERVAL '106 days'),
                                                                                                                           (7, 'Gita Kusuma', 'gita.pratama@email.com', 'hash_gita123', '100007', '+6281666666007', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gita', TRUE, NOW() - INTERVAL '102 days'),
                                                                                                                           (8, 'Hendra Putri', 'hendra.pratama@email.com', 'hash_hendra123', '100008', '+6281666666008', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hendra', FALSE, NOW() - INTERVAL '16 days'),
                                                                                                                           (9, 'Indah Pratama', 'indah.utami@email.com', 'hash_indah123', '100009', '+6281666666009', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Indah', TRUE, NOW() - INTERVAL '48 days'),
                                                                                                                           (10, 'Joko Kusuma', 'joko.utami@email.com', 'hash_joko123', '100010', '+6281666666010', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joko', TRUE, NOW() - INTERVAL '105 days'),
                                                                                                                           (11, 'Kartika Kusuma', 'kartika.saputra@email.com', 'hash_kartika123', '100011', '+6281666666011', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kartika', TRUE, NOW() - INTERVAL '24 days'),
                                                                                                                           (12, 'Luky Pratama', 'luky.wijaya@email.com', 'hash_luky123', '100012', '+6281666666012', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luky', FALSE, NOW() - INTERVAL '68 days'),
                                                                                                                           (13, 'Mega Pratama', 'mega.saputra@email.com', 'hash_mega123', '100013', '+6281666666013', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mega', TRUE, NOW() - INTERVAL '12 days'),
                                                                                                                           (14, 'Nugroho Putri', 'nugroho.utami@email.com', 'hash_nugroho123', '100014', '+6281666666014', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nugroho', TRUE, NOW() - INTERVAL '58 days'),
                                                                                                                           (15, 'Olivia Kusuma', 'olivia.pratama@email.com', 'hash_olivia123', '100015', '+6281666666015', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia', TRUE, NOW() - INTERVAL '147 days'),
                                                                                                                           (16, 'Prabowo Kusuma', 'prabowo.wijaya@email.com', 'hash_prabowo123', '100016', '+6281666666016', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prabowo', FALSE, NOW() - INTERVAL '14 days'),
                                                                                                                           (17, 'Rina Hidayat', 'rina.utami@email.com', 'hash_rina123', '100017', '+6281666666017', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rina', TRUE, NOW() - INTERVAL '149 days'),
                                                                                                                           (18, 'Surya Hidayat', 'surya.saputra@email.com', 'hash_surya123', '100018', '+6281666666018', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Surya', TRUE, NOW() - INTERVAL '177 days'),
                                                                                                                           (19, 'Tika Putri', 'tika.pratama@email.com', 'hash_tika123', '100019', '+6281666666019', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tika', TRUE, NOW() - INTERVAL '148 days'),
                                                                                                                           (20, 'Utomo Pratama', 'utomo.utami@email.com', 'hash_utomo123', '100020', '+6281666666020', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Utomo', FALSE, NOW() - INTERVAL '53 days');

ALTER SEQUENCE users_id_seq RESTART WITH 21;

-- 2. INSERT OAUTH_USER
INSERT INTO oauth_user (user_id, provider_name, provider_user_id, access_token, refresh_token, created_at) VALUES
                                                                                                               (1, 'facebook', 'oauth_id_1001', 'access_tok_1', 'refresh_tok_1', NOW() - INTERVAL '30 days'),
                                                                                                               (2, 'google', 'oauth_id_1002', 'access_tok_2', 'refresh_tok_2', NOW() - INTERVAL '30 days'),
                                                                                                               (3, 'facebook', 'oauth_id_1003', 'access_tok_3', 'refresh_tok_3', NOW() - INTERVAL '30 days'),
                                                                                                               (4, 'google', 'oauth_id_1004', 'access_tok_4', 'refresh_tok_4', NOW() - INTERVAL '30 days'),
                                                                                                               (5, 'facebook', 'oauth_id_1005', 'access_tok_5', 'refresh_tok_5', NOW() - INTERVAL '30 days'),
                                                                                                               (6, 'google', 'oauth_id_1006', 'access_tok_6', 'refresh_tok_6', NOW() - INTERVAL '30 days'),
                                                                                                               (7, 'facebook', 'oauth_id_1007', 'access_tok_7', 'refresh_tok_7', NOW() - INTERVAL '30 days'),
                                                                                                               (8, 'google', 'oauth_id_1008', 'access_tok_8', 'refresh_tok_8', NOW() - INTERVAL '30 days'),
                                                                                                               (9, 'facebook', 'oauth_id_1009', 'access_tok_9', 'refresh_tok_9', NOW() - INTERVAL '30 days'),
                                                                                                               (10, 'google', 'oauth_id_1010', 'access_tok_10', 'refresh_tok_10', NOW() - INTERVAL '30 days'),
                                                                                                               (11, 'facebook', 'oauth_id_1011', 'access_tok_11', 'refresh_tok_11', NOW() - INTERVAL '30 days'),
                                                                                                               (12, 'google', 'oauth_id_1012', 'access_tok_12', 'refresh_tok_12', NOW() - INTERVAL '30 days'),
                                                                                                               (13, 'facebook', 'oauth_id_1013', 'access_tok_13', 'refresh_tok_13', NOW() - INTERVAL '30 days'),
                                                                                                               (14, 'google', 'oauth_id_1014', 'access_tok_14', 'refresh_tok_14', NOW() - INTERVAL '30 days'),
                                                                                                               (15, 'facebook', 'oauth_id_1015', 'access_tok_15', 'refresh_tok_15', NOW() - INTERVAL '30 days'),
                                                                                                               (16, 'google', 'oauth_id_1016', 'access_tok_16', 'refresh_tok_16', NOW() - INTERVAL '30 days'),
                                                                                                               (17, 'facebook', 'oauth_id_1017', 'access_tok_17', 'refresh_tok_17', NOW() - INTERVAL '30 days'),
                                                                                                               (18, 'google', 'oauth_id_1018', 'access_tok_18', 'refresh_tok_18', NOW() - INTERVAL '30 days'),
                                                                                                               (19, 'facebook', 'oauth_id_1019', 'access_tok_19', 'refresh_tok_19', NOW() - INTERVAL '30 days'),
                                                                                                               (20, 'google', 'oauth_id_1020', 'access_tok_20', 'refresh_tok_20', NOW() - INTERVAL '30 days');

-- 3. INSERT FORGOT_PASSWORD
INSERT INTO forgot_password (user_id, token, is_used, created_at, expired_at) VALUES
                                                                                  (8, 'token_xyz_1', FALSE, NOW() - INTERVAL '1 days', NOW() - INTERVAL '1 days' + INTERVAL '1 hour'),
                                                                                  (20, 'token_xyz_2', FALSE, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '1 hour'),
                                                                                  (12, 'token_xyz_3', TRUE, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days' + INTERVAL '1 hour'),
                                                                                  (19, 'token_xyz_4', FALSE, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days' + INTERVAL '1 hour'),
                                                                                  (9, 'token_xyz_5', FALSE, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days' + INTERVAL '1 hour'),
                                                                                  (4, 'token_xyz_6', TRUE, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days' + INTERVAL '1 hour'),
                                                                                  (5, 'token_xyz_7', FALSE, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days' + INTERVAL '1 hour'),
                                                                                  (8, 'token_xyz_8', FALSE, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days' + INTERVAL '1 hour'),
                                                                                  (10, 'token_xyz_9', TRUE, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days' + INTERVAL '1 hour'),
                                                                                  (18, 'token_xyz_10', FALSE, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days' + INTERVAL '1 hour'),
                                                                                  (12, 'token_xyz_11', FALSE, NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days' + INTERVAL '1 hour'),
                                                                                  (12, 'token_xyz_12', TRUE, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days' + INTERVAL '1 hour'),
                                                                                  (11, 'token_xyz_13', FALSE, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days' + INTERVAL '1 hour'),
                                                                                  (7, 'token_xyz_14', FALSE, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days' + INTERVAL '1 hour'),
                                                                                  (14, 'token_xyz_15', TRUE, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days' + INTERVAL '1 hour'),
                                                                                  (4, 'token_xyz_16', FALSE, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days' + INTERVAL '1 hour'),
                                                                                  (2, 'token_xyz_17', FALSE, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days' + INTERVAL '1 hour'),
                                                                                  (12, 'token_xyz_18', TRUE, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days' + INTERVAL '1 hour'),
                                                                                  (3, 'token_xyz_19', FALSE, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days' + INTERVAL '1 hour'),
                                                                                  (6, 'token_xyz_20', FALSE, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days' + INTERVAL '1 hour');

-- 4. INSERT REVIEWS
INSERT INTO reviews (user_id, rating, description, created_at) VALUES
                                                                   (7, 4, 'Suka dengan tampilannya ke-1', NOW() - INTERVAL '1 days'),
                                                                   (3, 5, 'Suka dengan tampilannya ke-2', NOW() - INTERVAL '2 days'),
                                                                   (17, 4, 'Sangat membantu mengatur keuangan ke-3', NOW() - INTERVAL '3 days'),
                                                                   (7, 5, 'Aplikasi sangat bagus! ke-4', NOW() - INTERVAL '4 days'),
                                                                   (6, 3, 'Transfernya cepat sekali ke-5', NOW() - INTERVAL '5 days'),
                                                                   (1, 4, 'Sangat membantu mengatur keuangan ke-6', NOW() - INTERVAL '6 days'),
                                                                   (8, 4, 'Aplikasi sangat bagus! ke-7', NOW() - INTERVAL '7 days'),
                                                                   (5, 5, 'Sangat membantu mengatur keuangan ke-8', NOW() - INTERVAL '8 days'),
                                                                   (6, 4, 'Transfernya cepat sekali ke-9', NOW() - INTERVAL '9 days'),
                                                                   (16, 3, 'Transfernya cepat sekali ke-10', NOW() - INTERVAL '10 days'),
                                                                   (6, 4, 'Transfernya cepat sekali ke-11', NOW() - INTERVAL '11 days'),
                                                                   (18, 5, 'Sangat membantu mengatur keuangan ke-12', NOW() - INTERVAL '12 days'),
                                                                   (13, 4, 'Aplikasi sangat bagus! ke-13', NOW() - INTERVAL '13 days'),
                                                                   (17, 5, 'Suka dengan tampilannya ke-14', NOW() - INTERVAL '14 days'),
                                                                   (6, 3, 'Sangat membantu mengatur keuangan ke-15', NOW() - INTERVAL '15 days'),
                                                                   (17, 4, 'Suka dengan tampilannya ke-16', NOW() - INTERVAL '16 days'),
                                                                   (3, 5, 'Mudah digunakan untuk topup ke-17', NOW() - INTERVAL '17 days'),
                                                                   (10, 5, 'Sangat membantu mengatur keuangan ke-18', NOW() - INTERVAL '18 days'),
                                                                   (12, 4, 'Aplikasi sangat bagus! ke-19', NOW() - INTERVAL '19 days'),
                                                                   (19, 3, 'Sangat membantu mengatur keuangan ke-20', NOW() - INTERVAL '20 days');

-- 5. INSERT NEWSLETTER
INSERT INTO newsletter (user_id, email, status, created_at) VALUES
                                                                (1, 'news_user1@example.com', 'active', NOW() - INTERVAL '5 days'),
                                                                (2, 'news_user2@example.com', 'active', NOW() - INTERVAL '10 days'),
                                                                (3, 'news_user3@example.com', 'active', NOW() - INTERVAL '15 days'),
                                                                (4, 'news_user4@example.com', 'unsubscribe', NOW() - INTERVAL '20 days'),
                                                                (5, 'news_user5@example.com', 'active', NOW() - INTERVAL '25 days'),
                                                                (6, 'news_user6@example.com', 'active', NOW() - INTERVAL '30 days'),
                                                                (7, 'news_user7@example.com', 'active', NOW() - INTERVAL '35 days'),
                                                                (8, 'news_user8@example.com', 'unsubscribe', NOW() - INTERVAL '40 days'),
                                                                (9, 'news_user9@example.com', 'active', NOW() - INTERVAL '45 days'),
                                                                (10, 'news_user10@example.com', 'active', NOW() - INTERVAL '50 days'),
                                                                (11, 'news_user11@example.com', 'active', NOW() - INTERVAL '55 days'),
                                                                (12, 'news_user12@example.com', 'unsubscribe', NOW() - INTERVAL '60 days'),
                                                                (13, 'news_user13@example.com', 'active', NOW() - INTERVAL '65 days'),
                                                                (14, 'news_user14@example.com', 'active', NOW() - INTERVAL '70 days'),
                                                                (15, 'news_user15@example.com', 'active', NOW() - INTERVAL '75 days'),
                                                                (16, 'news_user16@example.com', 'unsubscribe', NOW() - INTERVAL '80 days'),
                                                                (17, 'news_user17@example.com', 'active', NOW() - INTERVAL '85 days'),
                                                                (18, 'news_user18@example.com', 'active', NOW() - INTERVAL '90 days'),
                                                                (19, 'news_user19@example.com', 'active', NOW() - INTERVAL '95 days'),
                                                                (20, 'news_user20@example.com', 'unsubscribe', NOW() - INTERVAL '100 days');

-- 6. INSERT WALLET
INSERT INTO wallet (user_id, balance, created_at, updated_at) VALUES
                                                                  (1, 5750000.0, NOW() - INTERVAL '200 days', NOW()),
                                                                  (2, 735600.65, NOW() - INTERVAL '200 days', NOW()),
                                                                  (3, 1191514.4, NOW() - INTERVAL '200 days', NOW()),
                                                                  (4, 1551616.23, NOW() - INTERVAL '200 days', NOW()),
                                                                  (5, 1798470.77, NOW() - INTERVAL '200 days', NOW()),
                                                                  (6, 805518.68, NOW() - INTERVAL '200 days', NOW()),
                                                                  (7, 409610.61, NOW() - INTERVAL '200 days', NOW()),
                                                                  (8, 157975.64, NOW() - INTERVAL '200 days', NOW()),
                                                                  (9, 584545.16, NOW() - INTERVAL '200 days', NOW()),
                                                                  (10, 625355.95, NOW() - INTERVAL '200 days', NOW()),
                                                                  (11, 1317475.66, NOW() - INTERVAL '200 days', NOW()),
                                                                  (12, 202944.8, NOW() - INTERVAL '200 days', NOW()),
                                                                  (13, 404736.0, NOW() - INTERVAL '200 days', NOW()),
                                                                  (14, 1132083.68, NOW() - INTERVAL '200 days', NOW()),
                                                                  (15, 331048.31, NOW() - INTERVAL '200 days', NOW()),
                                                                  (16, 1791732.26, NOW() - INTERVAL '200 days', NOW()),
                                                                  (17, 1678342.61, NOW() - INTERVAL '200 days', NOW()),
                                                                  (18, 835569.17, NOW() - INTERVAL '200 days', NOW()),
                                                                  (19, 603233.85, NOW() - INTERVAL '200 days', NOW()),
                                                                  (20, 1987809.32, NOW() - INTERVAL '200 days', NOW());

-- 7. INSERT CATEGORY_PAYMENT_METHOD
INSERT INTO category_payment_method (id, category_name, created_at) VALUES
                                                                        (1, 'Bank Transfer', NOW()),
                                                                        (2, 'E-Wallet', NOW()),
                                                                        (3, 'Convenience Store', NOW()),
                                                                        (4, 'Credit Card', NOW()),
                                                                        (5, 'Instant Payment', NOW());
ALTER SEQUENCE category_payment_method_id_seq RESTART WITH 6;

-- 8. INSERT PAYMENT_METHOD
INSERT INTO payment_method (id, payment_category_id, name, code, fee, logo_url, is_active, created_at) VALUES
                                                                                                           (1, 1, 'BCA Virtual Account', 'BCAVA', 1000.0, 'https://logo.url/bcava.png', TRUE, NOW()),
                                                                                                           (2, 1, 'Mandiri Virtual Account', 'MANDIRIVA', 1000.0, 'https://logo.url/mandiriva.png', TRUE, NOW()),
                                                                                                           (3, 1, 'BNI Virtual Account', 'BNIVA', 1000.0, 'https://logo.url/bniva.png', TRUE, NOW()),
                                                                                                           (4, 1, 'BRI Virtual Account', 'BRIVA', 1000.0, 'https://logo.url/briva.png', TRUE, NOW()),
                                                                                                           (5, 1, 'Permata Virtual Account', 'PERMATAVA', 1000.0, 'https://logo.url/permatava.png', TRUE, NOW()),
                                                                                                           (6, 2, 'GoPay', 'GOPAY', 1500.0, 'https://logo.url/gopay.png', TRUE, NOW()),
                                                                                                           (7, 2, 'OVO', 'OVO', 1500.0, 'https://logo.url/ovo.png', TRUE, NOW()),
                                                                                                           (8, 2, 'Dana', 'DANA', 1000.0, 'https://logo.url/dana.png', TRUE, NOW()),
                                                                                                           (9, 2, 'LinkAja', 'LINKAJA', 1000.0, 'https://logo.url/linkaja.png', TRUE, NOW()),
                                                                                                           (10, 2, 'ShopeePay', 'SPAY', 2000.0, 'https://logo.url/spay.png', TRUE, NOW()),
                                                                                                           (11, 3, 'Indomaret', 'IDM', 2500.0, 'https://logo.url/idm.png', TRUE, NOW()),
                                                                                                           (12, 3, 'Alfamart', 'ALFA', 2500.0, 'https://logo.url/alfa.png', TRUE, NOW()),
                                                                                                           (13, 4, 'Visa Card', 'VISA', 5000.0, 'https://logo.url/visa.png', TRUE, NOW()),
                                                                                                           (14, 4, 'MasterCard', 'MC', 5000.0, 'https://logo.url/mc.png', TRUE, NOW()),
                                                                                                           (15, 4, 'JCB Card', 'JCB', 6000.0, 'https://logo.url/jcb.png', TRUE, NOW()),
                                                                                                           (16, 5, 'QRIS', 'QRIS', 0.0, 'https://logo.url/qris.png', TRUE, NOW()),
                                                                                                           (17, 5, 'BI-Fast', 'BIFAST', 2500.0, 'https://logo.url/bifast.png', TRUE, NOW()),
                                                                                                           (18, 1, 'CIMB Niaga VA', 'CIMBVA', 1000.0, 'https://logo.url/cimbva.png', TRUE, NOW()),
                                                                                                           (19, 2, 'Sakuku', 'SAKUKU', 1000.0, 'https://logo.url/sakuku.png', TRUE, NOW()),
                                                                                                           (20, 3, 'Lawson', 'LAWSON', 2500.0, 'https://logo.url/lawson.png', TRUE, NOW());
ALTER SEQUENCE payment_method_id_seq RESTART WITH 21;

-- 9. INSERT TRANSACTIONS, TRANSFER_DETAILS, TOPUP_DETAILS
/* Generating transactions manually to maintain strict constraint integrity */
INSERT INTO transactions (id, user_id, amount, type, activity_type, status, created_at) VALUES
                                                                                            (1, 2, 50000.00, 'income', 'topup', 'success', NOW() - INTERVAL '33 days'),
                                                                                            (2, 3, 50000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '31 days'),
                                                                                            (3, 4, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '11 days'),
                                                                                            (4, 5, 250000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '48 days'),
                                                                                            (5, 6, 50000.00, 'income', 'topup', 'success', NOW() - INTERVAL '40 days'),
                                                                                            (6, 7, 250000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '20 days'),
                                                                                            (7, 8, 100000.00, 'income', 'topup', 'success', NOW() - INTERVAL '11 days'),
                                                                                            (8, 9, 500000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '18 days'),
                                                                                            (9, 10, 250000.00, 'income', 'topup', 'success', NOW() - INTERVAL '29 days'),
                                                                                            (10, 11, 500000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '43 days'),
                                                                                            (11, 12, 50000.00, 'income', 'topup', 'success', NOW() - INTERVAL '34 days'),
                                                                                            (12, 13, 100000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '44 days'),
                                                                                            (13, 14, 50000.00, 'income', 'topup', 'success', NOW() - INTERVAL '35 days'),
                                                                                            (14, 15, 100000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '7 days'),
                                                                                            (15, 16, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '34 days'),
                                                                                            (16, 17, 50000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '23 days'),
                                                                                            (17, 18, 50000.00, 'income', 'topup', 'success', NOW() - INTERVAL '34 days'),
                                                                                            (18, 19, 250000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '12 days'),
                                                                                            (19, 20, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '26 days'),
                                                                                            (20, 1, 1000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '1 days'),
                                                                                            (21, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '2 days'),
                                                                                            (22, 1, 400000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '3 days'),
                                                                                            (23, 1, 700000.00, 'income', 'topup', 'success', NOW() - INTERVAL '4 days'),
                                                                                            (24, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '5 days'),
                                                                                            (25, 1, 300000.00, 'income', 'topup', 'success', NOW() - INTERVAL '6 days'),
                                                                                            (26, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '8 days'),
                                                                                            (27, 1, 300000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '9 days'),
                                                                                            (28, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '10 days'),
                                                                                            (29, 1, 500000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '11 days'),
                                                                                            (30, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '12 days'),
                                                                                            (31, 1, 1200000.00, 'income', 'topup', 'success', NOW() - INTERVAL '15 days'),
                                                                                            (32, 1, 600000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '17 days'),
                                                                                            (33, 1, 800000.00, 'income', 'topup', 'success', NOW() - INTERVAL '19 days'),
                                                                                            (34, 1, 3000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '25 days'),
                                                                                            (35, 1, 1500000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '26 days'),
                                                                                            (36, 1, 500000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '28 days'),
                                                                                            (37, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '35 days'),
                                                                                            (38, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '40 days'),
                                                                                            (39, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '48 days'),
                                                                                            (40, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '52 days'),
                                                                                            (41, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '65 days'),
                                                                                            (42, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '70 days'),
                                                                                            (43, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '78 days'),
                                                                                            (44, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '82 days'),
                                                                                            (45, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '95 days'),
                                                                                            (46, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '100 days'),
                                                                                            (47, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '108 days'),
                                                                                            (48, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '112 days'),
                                                                                            (49, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '125 days'),
                                                                                            (50, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '130 days'),
                                                                                            (51, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '138 days'),
                                                                                            (52, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '142 days'),
                                                                                            (53, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '155 days'),
                                                                                            (54, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '160 days'),
                                                                                            (55, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '168 days'),
                                                                                            (56, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '172 days'),
                                                                                            (57, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '185 days'),
                                                                                            (58, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '190 days'),
                                                                                            (59, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '198 days'),
                                                                                            (60, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '202 days'),
                                                                                            (61, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '215 days'),
                                                                                            (62, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '220 days'),
                                                                                            (63, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '228 days'),
                                                                                            (64, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '232 days'),
                                                                                            (65, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '245 days'),
                                                                                            (66, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '250 days'),
                                                                                            (67, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '258 days'),
                                                                                            (68, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '262 days'),
                                                                                            (69, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '275 days'),
                                                                                            (70, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '280 days'),
                                                                                            (71, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '288 days'),
                                                                                            (72, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '292 days'),
                                                                                            (73, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '305 days'),
                                                                                            (74, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '310 days'),
                                                                                            (75, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '318 days'),
                                                                                            (76, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '322 days'),
                                                                                            (77, 1, 4000000.00, 'income', 'topup', 'success', NOW() - INTERVAL '335 days'),
                                                                                            (78, 1, 1200000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '340 days'),
                                                                                            (79, 1, 800000.00, 'expense', 'transfer', 'success', NOW() - INTERVAL '348 days'),
                                                                                            (80, 1, 500000.00, 'income', 'topup', 'success', NOW() - INTERVAL '352 days');

INSERT INTO transfer_details (transaction_id, receiver_id, description, created_at) VALUES
                                                                                        (2, 1, 'Transfer baseline dari user 3', NOW() - INTERVAL '31 days'),
                                                                                        (4, 1, 'Transfer baseline dari user 5', NOW() - INTERVAL '48 days'),
                                                                                        (6, 1, 'Transfer baseline dari user 7', NOW() - INTERVAL '20 days'),
                                                                                        (8, 1, 'Transfer baseline dari user 9', NOW() - INTERVAL '18 days'),
                                                                                        (10, 1, 'Transfer baseline dari user 11', NOW() - INTERVAL '43 days'),
                                                                                        (12, 1, 'Transfer baseline dari user 13', NOW() - INTERVAL '44 days'),
                                                                                        (14, 1, 'Transfer baseline dari user 15', NOW() - INTERVAL '7 days'),
                                                                                        (16, 1, 'Transfer baseline dari user 17', NOW() - INTERVAL '23 days'),
                                                                                        (18, 1, 'Transfer baseline dari user 19', NOW() - INTERVAL '12 days'),
                                                                                        (22, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '3 days'),
                                                                                        (24, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '5 days'),
                                                                                        (27, 4, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '9 days'),
                                                                                        (29, 5, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '11 days'),
                                                                                        (32, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '17 days'),
                                                                                        (35, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '26 days'),
                                                                                        (36, 10, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '28 days'),
                                                                                        (38, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '40 days'),
                                                                                        (39, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '48 days'),
                                                                                        (42, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '70 days'),
                                                                                        (43, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '78 days'),
                                                                                        (46, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '100 days'),
                                                                                        (47, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '108 days'),
                                                                                        (50, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '130 days'),
                                                                                        (51, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '138 days'),
                                                                                        (54, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '160 days'),
                                                                                        (55, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '168 days'),
                                                                                        (58, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '190 days'),
                                                                                        (59, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '198 days'),
                                                                                        (62, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '220 days'),
                                                                                        (63, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '228 days'),
                                                                                        (66, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '250 days'),
                                                                                        (67, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '258 days'),
                                                                                        (70, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '280 days'),
                                                                                        (71, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '288 days'),
                                                                                        (74, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '310 days'),
                                                                                        (75, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '318 days'),
                                                                                        (78, 2, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '340 days'),
                                                                                        (79, 3, 'Transfer bulanan / kebutuhan harian', NOW() - INTERVAL '348 days');

INSERT INTO topup_details (transaction_id, payment_method_id, order_amount, delivery_fee, tax_amount, total_amount, created_at) VALUES
                                                                                                                                    (1, 3, 50000.00, 0.00, 0.00, 50000.00, NOW() - INTERVAL '33 days'),
                                                                                                                                    (3, 1, 500000.00, 0.00, 0.00, 500000.00, NOW() - INTERVAL '11 days'),
                                                                                                                                    (5, 2, 50000.00, 0.00, 0.00, 50000.00, NOW() - INTERVAL '40 days'),
                                                                                                                                    (7, 5, 100000.00, 0.00, 0.00, 100000.00, NOW() - INTERVAL '11 days'),
                                                                                                                                    (9, 4, 250000.00, 0.00, 0.00, 250000.00, NOW() - INTERVAL '29 days'),
                                                                                                                                    (11, 1, 50000.00, 0.00, 0.00, 50000.00, NOW() - INTERVAL '34 days'),
                                                                                                                                    (13, 5, 50000.00, 0.00, 0.00, 50000.00, NOW() - INTERVAL '35 days'),
                                                                                                                                    (15, 2, 500000.00, 0.00, 0.00, 500000.00, NOW() - INTERVAL '34 days'),
                                                                                                                                    (17, 5, 50000.00, 0.00, 0.00, 50000.00, NOW() - INTERVAL '34 days'),
                                                                                                                                    (19, 1, 500000.00, 0.00, 0.00, 500000.00, NOW() - INTERVAL '26 days'),
                                                                                                                                    (20, 1, 1000000.00, 1000.0, 0.00, 1001000.0, NOW() - INTERVAL '1 days'),
                                                                                                                                    (21, 6, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '2 days'),
                                                                                                                                    (23, 8, 700000.00, 1000.0, 0.00, 701000.0, NOW() - INTERVAL '4 days'),
                                                                                                                                    (25, 16, 300000.00, 1000.0, 0.00, 301000.0, NOW() - INTERVAL '6 days'),
                                                                                                                                    (26, 1, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '8 days'),
                                                                                                                                    (28, 6, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '10 days'),
                                                                                                                                    (30, 7, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '12 days'),
                                                                                                                                    (31, 2, 1200000.00, 1000.0, 0.00, 1201000.0, NOW() - INTERVAL '15 days'),
                                                                                                                                    (33, 8, 800000.00, 1000.0, 0.00, 801000.0, NOW() - INTERVAL '19 days'),
                                                                                                                                    (34, 1, 3000000.00, 1000.0, 0.00, 3001000.0, NOW() - INTERVAL '25 days'),
                                                                                                                                    (37, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '35 days'),
                                                                                                                                    (40, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '52 days'),
                                                                                                                                    (41, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '65 days'),
                                                                                                                                    (44, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '82 days'),
                                                                                                                                    (45, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '95 days'),
                                                                                                                                    (48, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '112 days'),
                                                                                                                                    (49, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '125 days'),
                                                                                                                                    (52, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '142 days'),
                                                                                                                                    (53, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '155 days'),
                                                                                                                                    (56, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '172 days'),
                                                                                                                                    (57, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '185 days'),
                                                                                                                                    (60, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '202 days'),
                                                                                                                                    (61, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '215 days'),
                                                                                                                                    (64, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '232 days'),
                                                                                                                                    (65, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '245 days'),
                                                                                                                                    (68, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '262 days'),
                                                                                                                                    (69, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '275 days'),
                                                                                                                                    (72, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '292 days'),
                                                                                                                                    (73, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '305 days'),
                                                                                                                                    (76, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '322 days'),
                                                                                                                                    (77, 1, 4000000.00, 1000.0, 0.00, 4001000.0, NOW() - INTERVAL '335 days'),
                                                                                                                                    (80, 16, 500000.00, 1000.0, 0.00, 501000.0, NOW() - INTERVAL '352 days');

ALTER SEQUENCE transactions_id_seq RESTART WITH 81;

-- 10. INSERT FAVORITE_CONTACTS
INSERT INTO favorite_contacts (user_id, favorite_user_id, created_at) VALUES
                                                                          (1, 2, NOW()),
                                                                          (1, 3, NOW()),
                                                                          (1, 4, NOW()),
                                                                          (1, 5, NOW()),
                                                                          (2, 1, NOW()),
                                                                          (2, 3, NOW()),
                                                                          (2, 4, NOW()),
                                                                          (2, 5, NOW()),
                                                                          (3, 1, NOW()),
                                                                          (3, 2, NOW()),
                                                                          (3, 4, NOW()),
                                                                          (3, 5, NOW()),
                                                                          (4, 1, NOW()),
                                                                          (4, 2, NOW()),
                                                                          (4, 3, NOW()),
                                                                          (4, 5, NOW()),
                                                                          (5, 1, NOW()),
                                                                          (5, 2, NOW()),
                                                                          (5, 3, NOW()),
                                                                          (5, 4, NOW());


