name: success message
on: [push]
jobs:
  say-success:
    runs-on: ubuntu-latest
    steps:
      - name: SayHello
        run: echo "Your Push success"
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: SayHello ${{ github.repository }}
        run: echo "Hello ${{ github.repository }}"